// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBegpDiKQgnh_Nu1-PFYTMV0UW_zdnVRlc',
    appId: '1:705710462644:web:86ebdc387603b5346a29e1',
    messagingSenderId: '705710462644',
    projectId: 'focusbloom-da987',
    authDomain: 'focusbloom-da987.firebaseapp.com',
    storageBucket: 'focusbloom-da987.firebasestorage.app',
    measurementId: 'G-K5SHHY1R36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvAObnetdsApux4epPy6J56DtE-x644kE',
    appId: '1:74123284037:android:4a497fc29ecd6340ba5d2c',
    messagingSenderId: '74123284037',
    projectId: 'focusbloom123',
    storageBucket: 'focusbloom123.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBegpDiKQgnh_Nu1-PFYTMV0UW_zdnVRlc',
    appId: '1:705710462644:web:86ebdc387603b5346a29e1',
    messagingSenderId: '705710462644',
    projectId: 'focusbloom-da987',
    authDomain: 'focusbloom-da987.firebaseapp.com',
    storageBucket: 'focusbloom-da987.firebasestorage.app',
  );
}
